## 01wk-2 : 회귀분석

In [1]:
import torch
import matplotlib.pyplot as plt

In [2]:
torch.cuda.is_available()

True

## **1. 예비학습**

### **A. torch**

---

`-` 벡터

In [3]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

`-` 벡터의 덧셈

In [4]:
torch.tensor([1,2,3]) + torch.tensor([2,2,2])

tensor([3, 4, 5])

`-` 브로드캐스팅

In [5]:
torch.tensor([1,2,3]) + 2

tensor([3, 4, 5])

### **B. 벡터와 매트릭스**

---

`-` $3 \times 2$ matrix

In [6]:
torch.tensor([[1,2], [3,4], [5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

`-` $3 \times 1$ matrix = $3 \times 1$ column vector

In [7]:
torch.tensor([[1], [3], [5]])

tensor([[1],
        [3],
        [5]])

`-` $1 \times 2$ matrix = $1 \times 2$ raw vector

In [8]:
torch.tensor([[1,2]])

tensor([[1, 2]])

`-` 더하기

**브로드캐스팅**

In [ ]:
## 전역에서 연산
torch.tensor([[1,2],
              [3,4],
              [5,6]]) - 1

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
## 각 열에 컬럼벡터를 연산
torch.tensor([[1,2],
              [3,4],
              [5,6]]) + torch.tensor([[-1],
                                      [-3],
                                      [-5]])

tensor([[0, 1],
        [0, 1],
        [0, 1]])

In [11]:
## 각 행에 행벡터를 연산
torch.tensor([[1,2],
              [3,4],
              [5,6]]) + torch.tensor([[-1, -2]])

tensor([[0, 0],
        [2, 2],
        [4, 4]])

<span style="color:red">**잘못된 브로드캐스팅**</span>

In [ ]:
## 행의 차원이 안맞는 경우(더 많음)
torch.tensor([[1,2],
              [3,4],
              [5,6]]) + torch.tensor([[-1, -3, -5]])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [ ]:
## 열의 차원이 안맞는 경우(더 적음)
torch.tensor([[1,2],
              [3,4],
              [5,6]]) + torch.tensor([[-1],
                                      [-2]])

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [ ]:
## 이런건 안되네...
torch.tensor([[1,2,3,4],
              [5,6,7,8]]) + torch.tensor([[1,2]])

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

***이상한 거***

In [ ]:
torch.tensor([[1,2],
              [3,4],
              [5,6]]) + torch.tensor([-1,-2])

tensor([[0, 0],
        [2, 2],
        [4, 4]])

> 그냥 벡터이지만, 비슷하게 됨. 일반적으로 열벡터를 의미하나, 그냥 행벡터인 것처럼 먹여버림.

In [15]:
torch.tensor([[1,2],
              [3,4],
              [5,6]]) + torch.tensor([-1,-3,-5])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

> 이쪽은 안됨. 약간 CS 분야에선 행벡터 위주로 취급하니까 이래 되는 것 같음. 아마도...
>
> 애초에 쓰지 말자!

`-` 행렬곱

**정상적인 행렬곱**

In [18]:
torch.tensor([[1,2],
              [3,4],
              [5,6]]) @ torch.tensor([[1],
                                      [2]])

tensor([[ 5],
        [11],
        [17]])

In [19]:
torch.tensor([[1,2,3]]) @ torch.tensor([[1,2],[3,4],[5,6]]) 

tensor([[22, 28]])

***잘못된 행렬곱***

In [ ]:
## 차원 안맞음 3X2 1X2
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([[1,2]])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 1x2)

In [ ]:
## 차원 안맞음 (3,1) X (3,2)
torch.tensor([[1],[2],[3]]) @ torch.tensor([[1,2],[3,4],[5,6]])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x1 and 3x2)

***또 이상한 거***

In [22]:
torch.tensor([[1,2],
              [3,4],
              [5,6]]) @ torch.tensor([1,2]) ## 벡터인데??

tensor([ 5, 11, 17])

> length가 2인 열벡터처럼 해석

In [23]:
torch.tensor([1,2,3]) @ torch.tensor([[1,2],
                                      [3,4],
                                      [5,6]]) ## 이건 덧셈이랑은 또 달리 범용적임

tensor([22, 28])

> 여기선 행벡터로 해석

### **C. transpose, reshape**

---

`-` transpose

In [24]:
torch.tensor([[1,2],
              [3,4]]).T

tensor([[1, 3],
        [2, 4]])

In [25]:
torch.tensor([[1],
              [3]]).T

tensor([[1, 3]])

In [26]:
torch.tensor([[1,2]]).T

tensor([[1],
        [2]])

`-` reshape

**일반적인 사용**

In [ ]:
torch.tensor([[1,2],
              [3,4],
              [5,6]]).reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [28]:
torch.tensor([[1,2],
              [3,4],
              [5,6]]).reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [29]:
torch.tensor([[1,2],
              [3,4],
              [5,6]]).reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

**편한 거**

In [ ]:
torch.tensor([[1,2],
              [3,4],
              [5,6]]).reshape(6) ## 차원 축소

tensor([1, 2, 3, 4, 5, 6])

In [31]:
torch.tensor([[1,2],
              [3,4],
              [5,6]]).reshape(2, -1) ## 선행 차원만 제한하고, 나머지는 변동으로

tensor([[1, 2, 3],
        [4, 5, 6]])

In [32]:
torch.tensor([[1,2],
              [3,4],
              [5,6]]).reshape(-1, 6)

tensor([[1, 2, 3, 4, 5, 6]])

In [34]:
torch.tensor([[1,2],
              [3,4],
              [5,6]]).reshape(-1) ## 차원 축소, 전체 수 입력 안함

tensor([1, 2, 3, 4, 5, 6])

### **D. concat, stack ($\star\star\star$)**

---

`-` concat

In [ ]:
a = torch.tensor([[1],
                  [3],
                  [5]])
b = torch.tensor([[2],
                  [4],
                  [6]])

torch.concat([a, b], axis = 1) ## 차원을 변화시키지 않음

tensor([[1, 2],
        [3, 4],
        [5, 6]])

`-` stack

In [41]:
a = torch.tensor([1,3,5])
b = torch.tensor([2,4,6])

torch.stack([a, b], axis = 1) ## 차원을 추가함

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
print(a.shape) ## 1 dimension
torch.stack([a, b], axis = 1).shape ## 2 dimension

torch.Size([3])


torch.Size([3, 2])

In [54]:
c = torch.stack([a, b], axis = 1)

torch.stack([c, c, c, c], axis = 2)

tensor([[[1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [4, 4, 4, 4]],

        [[5, 5, 5, 5],
         [6, 6, 6, 6]]])

In [52]:
torch.stack([c, c, c, c], axis = 0).shape

torch.Size([4, 3, 2])