# **중간고사 이전 내용 총 정리**

In [2]:
import torch

## **Pre-Learning : 텐서**

### **A. 벡터**

`-` Vector 선언

In [ ]:
torch.tensor([1, 2, 3])

`-` Vector 덧셈

In [ ]:
torch.tensor([1, 2, 3]) + torch.tensor([2]*3)
torch.tensor([1, 2, 3]) + 2 ## 브로드캐스팅

### **B. 벡터와 매트릭스**

`-` 브로드 캐스팅

In [ ]:
## 브로드 캐스팅
torch.tensor([[1, 2],
              [3, 4],
              [5, 6]]) - 1

## 다른 연산
torch.tensor([[1, 2], [3, 4], [5, 6]])*0

In [ ]:
## 열별 브로드 캐스팅
torch.tensor([[1, 2], [3, 4], [5, 6]]) + torch.tensor([[-1],
                                                       [-3],
                                                       [-5]])

## 행별 브로드캐스팅
torch.tensor([[1, 2], [3, 4], [5, 6]]) + torch.tensor([[-1, -2]])

`-` 벡터와의 연산 : 열벡터로 취급

In [7]:
torch.tensor([[1, 2], [3, 4], [5, 6]]) + torch.tensor([1, 2])
torch.tensor([[1, 2], [3, 4], [5, 6]]) + torch.tensor([1, 2, 3]) ## 안됨

tensor([[2, 4],
        [4, 6],
        [6, 8]])

`-` 행렬곱

In [ ]:
## 정상적인 행렬곱
torch.tensor([[1, 2], [3, 4], [5, 6]]) @ torch.tensor([[1],
                                                       [2]])
torch.tensor([[1, 2], [3, 4], [5, 6]]) @ torch.tensor([1, 2]) ## 열벡터

`-` 벡터는 행렬곱 연산에서 열벡터도로, 행벡터로도 취급할 수 있음

In [ ]:
torch.tensor([[1, 2, 3]]) @ torch.tensor([[1, 2], [3, 4], [5, 6]])
torch.tensor([1, 2, 3]) @ torch.tensor([[1, 2], [3, 4], [5, 6]])

### **C. transpose, reshape**

`-` 전치

In [16]:
torch.tensor([[1, 2], [3, 4]]).T

tensor([[1, 3],
        [2, 4]])

`-` reshape

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(2,-1) ## [[1, 2, 3], [4, 5, 6]]
torch.tensor([[1,2],[3,4],[5,6]]).reshape(-1,6)
torch.tensor([[1,2],[3,4],[5,6]]).reshape(-1)

### **D. concat, stack**

`-` concat(차원 유지, 쉬움)

In [18]:
a = torch.tensor([[1], [3], [5]])
b = torch.tensor([[2], [4], [5]])
torch.concat([a, b], axis = 1)

tensor([[1, 2],
        [3, 4],
        [5, 5]])

`-` stack(차원 늘림, 어려움)

In [19]:
a = torch.tensor([1, 3, 5])
b = torch.tensor([2, 4, 6])
torch.stack([a, b], axis = 1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [21]:
torch.concat([a.reshape(3, 1), b.reshape(3, 1)], axis = 1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## **1. 회귀**

### **A. 내용**

`-` 선형회귀모형

$$\begin{align} y_i & = w_0 + w_1 x_i + \epsilon, ~ i = 1, 2, \cdots \\
{\bf y} & = {\bf WX + \epsilon}
\end{align}$$

In [ ]:
W = torch.tensor([[1.0], [2.0]])
X = torch.stack([torch.ones, x], axis = 1)